### ISSUE TITLE
Package should be regestered

### ISSUE THREAD

**Issue by dlnsk** [Daursu/database-config-loader#1]
Please, register this package on http://packalyst.com for install it with composer.

**Comment by Daursu** [comment]
I've forked this from another repository on stash. The package is already registered under `"hailwood/database-config-loader": "dev-master"`.

If you would like to download my fork then you can add this to your `composer.json`:

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Daursu/database-config-loader"
        }
```

**Comment by dlnsk** [comment]
Yes, I did it. But error occurred:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package daursu/database-config-loader could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by Daursu** [comment]
It sounds like you are trying to load the wrong package name. The name in `composer.json` should be `"hailwood/database-config-loader": "dev-master"`

**Comment by dlnsk** [comment]
You are right. Thanks a lot!
